name: Unit Test

on: [push, pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install gtest
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib
      - name: Run CMake
        run: cd tests && cmake CMakeLists.txt
      - name: Run make
        run: make
      - name: Run tests
        run: ./runTests
