name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install gtest
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib
    - name: Run CMake
      run: cmake --build ./build --target all
    - name: Run make
      run: cd build && make
    - name: Run tests
      run: cd build && ./runTests
